### ISSUE TITLE
Add "Default Photopath" to Properties

### ISSUE THREAD

**Issue by MattDHill** [viktorstrate/embassyos-photoview-wrapper#2]
With `copyable: true` and a description similar to:

"To grant your admin user access to all media contained in File Browser, copy this value into "Photo Path" during initial setup."

Then we can edit the Instructions to reflect the existence of this property. So instead of saying copy/paste this value, it could say, "During initial setup, enter the default photopath found in "Properties". This will grant your Photoview admin user access to all media contained in File Browser."

**Comment by viktorstrate** [comment]
Sounds good, I'd like a pull-request for this one, as I'm not sure on the syntax for this.
