### ISSUE TITLE
Deleting sole admin user results in unrecoverable state

### ISSUE THREAD

**Issue by MattDHill** [viktorstrate/embassyos-photoview-wrapper#3]
Since Photoview permits the deletion of its only admin user, this wrapper should have an Action for resetting Photoview to an uninitialized state. Otherwise, the only way out is to uninstall the service and reinstall.

Perhaps this should be a feature request to Photoview itself, to not allow a user to delete themselves when they are the only user.

**Comment by viktorstrate** [comment]
I agree adding a simple check to prevent the last admin from being deleted

**Comment by viktorstrate** [comment]
Moved to https://github.com/photoview/photoview/issues/337
